version: "3.3"
services:
  app:
    build: .
    restart: always
    ports:
      - "7000:8000"
    depends_on:
      - mysql
    env_file:
      - web-variables.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=moeuser
      - MYSQL_PASS=moepass
      - MYSQL_DB=database_links
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_test
      MYSQL_USER: moeuser
      MYSQL_DATABASE: database_links
      MYSQL_PASSWORD: moepass
    volumes:
      - ./data:/data/db
    # container_name: moe-mysql-app
    ports:
      - "3306:3306"