version: "3.2"

services:
  app:
    build: .
    container_name: NODEJS
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: appdb
    depends_on:
      - mysql
    ports:
      - "7000:7000"
    restart: always
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    # restart: always
    container_name: MYSQL
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_ROOT_PASSWORD: example_root_password
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: PHPMYADMIN
    environment:
      PMA_HOST: mysql
      MYSQL_USER: useradmin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: passwordroot
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:

volumes:
  my_db:
