version: "3.3"
services:
  app:
    build: .
    restart: always
    ports:
      - "7000:7000"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root 
      # MYSQL_USER: paul
      MYSQL_DATABASE: database_links
      # MYSQL_PASSWORD: ikPyD42F5i9uw8N8
    volumes:
      - ./data:/data/db
    ports:
      - "3306:3306"