version: "3.3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "7000:7000"
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./data:/data/db
    ports:
      - "3306:3306"